### PR TITLE
child health and imms data tab based on table data (not scurve)

### PR DESCRIPTION
**Pull request by lucindalawrie**
Hi Vicky,

I have updated the scripts so that the data tab shows the table data for child health and immunisations rather than the scurve data. 

I'm not sure whether to include this in this weeks release or wait until the data is updated next week. Let me know what you think, we can hold off on merging with the master if we decide to wait until next week.

Lucinda

### CODE REVIEW

**Comment by vaelliott** [comment]
I've been doing some updates to the immunisation branch which i now realise make checking this branch more tricky.  I think your suggestions look fine but i've included jaime too just to be sure.  Jaime this branch does funny things to my 6-in-1 scurve but i think thats just because I have updated my data files?

**Comment by vaelliott** [comment]
I think we should aim to merge this branch with our update today if possible

**Comment by lucindalawrie** [comment]
This should be an easy fix, even if it went to PRA as it is I could make these changes before it goes live on Wednesday?

**Comment by jvillacampa** [comment]
Sounds good!

**Comment by lucindalawrie** [comment]
Happy for this to be merged or will it cause issues for your immunisation branch @vaelliott ?

**Comment by jvillacampa** [comment]
Hi Lucinda, your latest changes look good, I think this is ready to be merged?

**Comment by lucindalawrie** [comment]
Yes - happy for this branch to be merged and closed 👍

**Pull request merged**
