### PR TITLE
Dose2 6in1

### PR DESCRIPTION
**Pull request by vaelliott**
Think this is ready for merging to master ahead of PRA on monday (oohh apart from i need to re-instate the tabs that i've commented out whilst the tab is previewed by immunisation community!).  There will be some merge conflicts because i changed the name of some variables because i think it makes it easier to recognise which immunisation dose you are dealing with.

### CODE REVIEW

**Comment by vaelliott** [comment]
great thank, yes all the immunisations extracts are generated on the same date.
I'll update the urls, take a look at the tooltip, and generate open data extracts, and resolve the merge conflicts.
I'm not quite sure what you mean by this though"Once the merge conflicts are resolved, the code for the data can be modified so it takes the second and third doses as well." ?

**Comment by jvillacampa** [comment]
The data tab where users can download the data takes now the immunisation and hv data (but not in this branch ). So when you deal with the merge you will be able to modify that code so in the data the 2nd and 3rd doses are ready. Does that make sense?

**Comment by vaelliott** [comment]
err sort of, i'll figure it out.

**Comment by jvillacampa** [comment]
hahaha, sorry my explanation is very awful. It can be summarised in: make the 2nd dose and third dose data available in the data tab

**Pull request merged**
