### PR TITLE
filepaths updates

### PR DESCRIPTION
**Pull request by laurad05**
(+ change of download data column title from pre2020 to 2018-2019 average)

### CODE REVIEW

**Comment by vaelliott** [comment]
some of the UCD/A&E extracts are provided as already zipped since the files are pretty massive...(>40MB) I haven't found it adds that much time to read in the files - but I hadn't thought about the fact the files are unzipped on to your local drive (but now i course i've looked and i see what you mean).
Would it make sense to just zip any files that are the big extracts of historic data but then most queries (except a&e) seem to then provide a weekly update file which is significantly smaller and won't need zipping?

**Comment by laurad05** [comment]
Ok, glad it still works for you guys. Seems safe to delete the other files now as i just copied and pasted them over.

**Comment by jvillacampa** [comment]
> 
> 
> some of the UCD/A&E extracts are provided as already zipped since the files are pretty massive...(>40MB) I haven't found it adds that much time to read in the files - but I hadn't thought about the fact the files are unzipped on to your local drive (but now i course i've looked and i see what you mean).
> Would it make sense to just zip any files that are the big extracts of historic data but then most queries (except a&e) seem to then provide a weekly update file which is significantly smaller and won't need zipping? @jvillacampa @laurad05

What if we saved these big CSVs as rds and then delete the big csvs? My problem with the unzipping is that when you deploy the app to upload everything in your folder including these files which risks us uploading things that we shouldn't and also slows down the app.

**Comment by vaelliott** [comment]
good point....jaimes plan of converting to RDS if course the best solution

**Pull request merged**
